[package]
name = "func-plot"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = {
    version = "6.0.0",
    optional = true,
    default-features = false,
    features = [
        "GLFW_BUILD_WAYLAND",
        "GLFW_BUILD_X11",
        "SUPPORT_MODULE_RSHAPES",
        "SUPPORT_MODULE_RTEXTURES",
        "SUPPORT_MODULE_RTEXT",
    ],
}

[features]
default = ["graphics"]
graphics = ["dep:raylib"]

[[bin]]
name = "func-plot"
path = "src/main.rs"
required-features = ["graphics"]
